name: Task 9
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --system
          playwright install chromium

      - name: Run tests
        run: pytest

      - name: Deploy Results to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
            branch: gh-pages
            folder: reports/